import io
import pandas as pd
from datetime import datetime
from fpdf import FPDF
from sqlalchemy.orm import Session
from backend.app.repositories.repositories import inventory_repo, supplier_repo
from backend.app.services.procurement_service import calculate_reorder_points

class ClinicPDFReport(FPDF):
    def header(self):
        # Draw green banner background
        self.set_fill_color(0, 128, 128) # Teal
        self.rect(0, 0, 210, 30, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 5, 'SMART PHARMACY MANAGEMENT PLATFORM', align='C', new_x="LMARGIN", new_y="NEXT")
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 5, 'Official Procurement & Restocking Order Report', align='C', new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} | Autogenerated on {datetime.now().strftime("%Y-%m-%d")}', align='C')

def generate_pdf_report_buffer(branch_id: int, tenant_id: int, tenant_name: str, branch_name: str, db: Session) -> io.BytesIO:
    """Generates an in-memory PDF procurement report."""
    reorder_suggestions = calculate_reorder_points(branch_id, tenant_id, db)
    
    pdf = ClinicPDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.ln(15)
    
    # Header Clinic metadata
    pdf.set_text_color(0, 77, 64)
    pdf.set_font('helvetica', 'B', 12)
    pdf.cell(0, 6, f"Tenant Group: {tenant_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Branch Location: {branch_name}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Table Header
    pdf.set_fill_color(0, 128, 128)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('helvetica', 'B', 9)
    pdf.cell(50, 8, 'Medicine Name', border=1, fill=True)
    pdf.cell(20, 8, 'Stock', border=1, fill=True, align='C')
    pdf.cell(20, 8, 'ROP', border=1, fill=True, align='C')
    pdf.cell(25, 8, 'Reorder Qty', border=1, fill=True, align='C')
    pdf.cell(30, 8, 'Supplier', border=1, fill=True)
    pdf.cell(45, 8, 'Status', border=1, fill=True, align='C', new_x="LMARGIN", new_y="NEXT")
    
    # Table rows
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('helvetica', '', 9)
    for idx, r in enumerate(reorder_suggestions):
        pdf.cell(50, 8, str(r["Medicine Name"]), border=1)
        pdf.cell(20, 8, str(r["Usable Stock"]), border=1, align='C')
        pdf.cell(20, 8, str(r["Reorder Point (ROP)"]), border=1, align='C')
        pdf.cell(25, 8, str(r["Recommended Qty"]), border=1, align='C')
        pdf.cell(30, 8, str(r["Supplier Name"]), border=1)
        pdf.cell(45, 8, str(r["Status"]), border=1, align='C', new_x="LMARGIN", new_y="NEXT")
        
    buffer = io.BytesIO()
    # Save PDF string to bytes buffer
    pdf_output = pdf.output()
    buffer.write(pdf_output)
    buffer.seek(0)
    return buffer

def generate_csv_report_buffer(branch_id: int, tenant_id: int, db: Session) -> bytes:
    """Generates an in-memory CSV file of procurement suggestions."""
    reorder_suggestions = calculate_reorder_points(branch_id, tenant_id, db)
    if not reorder_suggestions:
        df = pd.DataFrame(columns=["Medicine ID", "Medicine Name", "Usable Stock", "ROP", "Recommended Qty", "Supplier", "Status"])
    else:
        df = pd.DataFrame(reorder_suggestions)
        
    return df.to_csv(index=False).encode('utf-8')

def generate_excel_report_buffer(branch_id: int, tenant_id: int, db: Session) -> io.BytesIO:
    """Generates an in-memory Excel file of procurement suggestions."""
    reorder_suggestions = calculate_reorder_points(branch_id, tenant_id, db)
    if not reorder_suggestions:
        df = pd.DataFrame(columns=["Medicine ID", "Medicine Name", "Usable Stock", "ROP", "Recommended Qty", "Supplier", "Status"])
    else:
        df = pd.DataFrame(reorder_suggestions)
        
    buffer = io.BytesIO()
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name="Procurement Suggestions")
    buffer.seek(0)
    return buffer
